name: Post to Tumblr

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub UI
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC (customize as needed)

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot script
        run: |
          python bot.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TUMBLR_CONSUMER_KEY: ${{ secrets.TUMBLR_CONSUMER_KEY }}
          TUMBLR_CONSUMER_SECRET: ${{ secrets.TUMBLR_CONSUMER_SECRET }}
          TUMBLR_OAUTH_TOKEN: ${{ secrets.TUMBLR_OAUTH_TOKEN }}
          TUMBLR_OAUTH_SECRET: ${{ secrets.TUMBLR_OAUTH_SECRET }}
          TUMBLR_BLOG_NAME: ${{ secrets.TUMBLR_BLOG_NAME }}
